baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://weitzman.github.io" # the base hostname & protocol for your site
future: false
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
